# Generated by Django 3.2.15 on 2022-10-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_prefix_vlan_vlangroup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ipam.prefix'),
        ),
    ]
