# Generated by Django 3.2.15 on 2022-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0009_prefix__add_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPrefix',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ipam.prefix',),
        ),
        migrations.AddField(
            model_name='prefix',
            name='ip_family',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='is_ip',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
