# Generated by Django 3.2.15 on 2022-10-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0010_prefix__add_parent__flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_ips', to='ipam.prefix'),
        ),
    ]
